title: "Your Portfolio"
description: "Technical writing portfolio built with GitHub Pages."

remote_theme: just-the-docs/just-the-docs

url: "https://stefsaffern.github.io/Portfolio"

search_enabled: true
